### ISSUE TITLE
Very long words overflow from containers

### ISSUE THREAD

**Issue by keelanfh** [localgovdrupal/localgov_base#366]
Very long words overflow from their containers - spotted on Guide Overview pages. This is a very unrealistic scenario but I think there's nothing to lose by adding `overflow-wrap: break-word` somewhere. There might be other places where this is more likely to happen, with narrower elements?

![image](https://user-images.githubusercontent.com/19519457/217003323-ef0570a5-bc40-4487-b405-305ef9310e47.png)

**Comment by keelanfh** [comment]
We've now had this popping up in the 'real world' (on smaller mobile phones):

![MicrosoftTeams-image (8)](https://github.com/localgovdrupal/localgov_base/assets/19519457/ade03f50-3e16-4304-8871-87d3d1f0b2da)

![MicrosoftTeams-image (10)](https://github.com/localgovdrupal/localgov_base/assets/19519457/f3ad91c2-e498-49b1-9e71-bf0fed4b1ae8)

**Comment by andybroomfield** [comment]
The issue here is that adding overflow-wrap: break-work or simmilar results in long links breaking in the middle of words even when there are spaces, leading to tickets being raised like
> What change do you want to make?
There's a problem with hyperlinks and email addresses on the website. They are running over 2 lines splitting words up. 

The compromise at BHCC was to do this on email addresses only, and only on small screens:
````css
/* Allow long link titles to wrap on small screens. */
.rich-text__item a[href^="mailto:"] {
  display: inline-block;
  word-break: break-all;
}

/* Reset to default behaviour for larger screens */
@media only screen and (min-width: 768px) {
  .rich-text__item a[href^="mailto:"] {
    display: inline;
    word-break: normal;
  }
}
````
Beyond this, we would need javascript to add some invisible breaking spaces or wrap long words in classes to apply the break word behaviour.
